### ISSUE TITLE
TAP-GW: fetch messages

### ISSUE THREAD

**Issue by monkeypants** [ausdigital/ausdigital-tap#11]
One "epic" of the TAP-GW is receiving inbound messages.

In some ways, the TAP-GW interface is a lot like a POP inbox. A TAP-GW user authenticates with a valid bearer token that has legitimate claim to a single business identity "inbox". There is a list of messages, some of which are "marked as new" and some of which are "marked as already downloaded". There are methods for downloading and deleting messages from the inbox. That sort of thing.

We need to specify a REST API that is approximately similar to POP3 protocol, for fetching encrypted messages from the TAP-GW.

**Comment by koriaf** [comment]
current swagger spec already have some vision; I think after soon spec rewrite this task will be outdated

**Comment by monkeypants** [comment]
agreed

**Comment by monkeypants** [comment]
this ticket is on the wrong repo, and is outdated.
