### ISSUE TITLE
Representing the "conversationID" in the TAP protocol

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital-tap#15]
Whilst I agree it's important to limit information leakage to observers in the message pathway (eg gateways), I think there is a need for the "conversationID" concept.  It's purpose is to link related messages in a transaction that has an outcome.  For example all messages related to a single [invoice state lifecycle](http://ausdigital.org/specs/ausdigital-bill/1.0/) would have the same conversationID. 

* As a trade financer, I need a way to examine the notary to see all messages in an invoice transaction that I am factoring so that I can be sure that the seller isn't hiding an important state transition (eg from approved to disputed).
* As a seller ledger, I need a key to share with any number of interested third parties (eg competing factoring service providers) that identifies the collection of messages that represent the invoice I want to finance.
* As a buyer and seller ledger, I need a way to connect business semantics to message semantics with a unique and durable key such as a conversationID GUID so that I can share it with interested third parties and limit what they can see to just the transaction I want to share.

I note that there is a "reference" element in the TAP header defined in the [TAP Spec](http://ausdigital.org/specs/ausdigital-tap/2.0/).  But I am unsure whether this is meant for some other purpose or could / should be used as a conversationID?

**Comment by onthebreeze** [comment]
One option might be to keep the "reference" element in the TAP header as a very generic placeholder for any reference semantics for the payload.   And then leave it up to the consumer specification (in this case the BILL spec) to define how it should be use in a particular business context.  

So for example the BILL spec might say:

* The invoice state lifecycle defines the scope of an e-invoice "conversation"
* There should be a unique identifier for each "conversation" and it MUST be placed into the TAP header "reference" field
* The identifier SHOULD be a GUID but MAY be a URI of the form <mydomain>.<identifier> created by the initiator of the conversation.
* The identifier MUST be maintained by the participating (buyer and seller) ledgers as the durable link between the business layer and messaging layer.

or something like that..

**Comment by onthebreeze** [comment]
http://ausdigital.org/specs/ausdigital-bill/1.0/ - updated with "Transport Layer Bindings" paragraph.

This ticket can be closed when the TAP specification includes 

* Some words explaining that the guidance for population of the  "reference" field will be found in each semantic specification that leverages the TAP spec.
* One or two nice message envelope examples.

**Comment by monkeypants** [comment]
TAP needs a swagger spec! the current stub is empty. That's probably the best place for usage notes on the reference field.

Totally agree about message envelope examples.

**Comment by monkeypants** [comment]
This ticket is obsolete due to #18
