### ISSUE TITLE
Develop a swagger document for TAP 2.0 specification

### ISSUE THREAD

**Issue by kshychko** [ausdigital/ausdigital-tap#16]
Please create a document for http://ausdigital.org/specs/ausdigital-tap/2.0/

Once you confirm it is valid (it is easy to check it with swaggerhub), please update the following file:

https://github.com/ausdigital/ausdigital-tap/blob/master/docs/2.0/swagger.json

**Comment by krylataya** [comment]
Swagger.json updated.
