### ISSUE TITLE
Update TAP endpoint response format

### ISSUE THREAD

**Issue by koriaf** [ausdigital/ausdigital-tap#19]
Currently it is:
```
{
 "data": {
   "type": "TapMessage",
   "id": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX",
   "attributes": {
       "uuid": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXXX",
       "deliveryStatus": "in_transit"
   }
 }
}
```
But looks like it was meant to be:
```
{
 "data": {
   "type": "TapMessage",
   "id": "tap-gw or tap message id (received attempt id)",
   "attributes": {
       "messageHash": "value from the message.json file",
       "deliveryStatus": "transit"
   }
 }
}
```
So:
* message sending actions reference id, which is UUID generated by receiving party
* message receiving party has both fields, id and messageHash
* messageHash just forwared from submitted message.json file, `hash` field.
* callbacks operate with both fields, id and messageHash

@monkeypants, @onthebreeze  - please acknowledge. Putting it here to finally agree with it and do not lose such improvement.

**Comment by onthebreeze** [comment]
Looks good.  Here's a few other things to help clarify the TAP spec:

* lets add a full sample message to the spec.  Examples are always good.  Obviously the ciphertext bit would need to be truncated.
* yes, agree that 200 response to change from "uuid" to "messageHash"
* lets fix that [diagram](http://ausdigital.org/specs/ausdigital-tap/2.0/#tap-protocol-overview) in the spec to be consistent with the sample & schema
* lets add the new element "attachedTo" to the json message schema which must be a documentHash - as discussed in #18 
* update the [receipts](http://ausdigital.org/specs/ausdigital-tap/2.0/#receipt-and-technical-acknowledgement) part of the spec  part of the spec with clear description of all these IDs.

**Comment by onthebreeze** [comment]
I think a state lifecycle is handy.  Something like the attached image.

Also, there should be no overlap between TAP message lifecycle and business document lifecycle (eg [BILL Lifecycle](http://ausdigital.org/specs/ausdigital-bill/1.0/#state-lifecycle)) 

TAP is only about getting the message between access points with a valid signature.
![statechartdiagram1](https://cloud.githubusercontent.com/assets/13426392/25562711/dcc5c362-2dd0-11e7-97c4-3841a577b21b.png)

**Comment by onthebreeze** [comment]
But se do need to properly enumerate all the 

* http error codes
* callback error codes

**Comment by monkeypants** [comment]
![image](https://cloud.githubusercontent.com/assets/532596/25563657/d567a3d4-2de3-11e7-8e71-be92053b0068.png)

**Comment by koriaf** [comment]
Hm. Do it messageHash or documentHash?
The document is the thing from 'cyphertext' before the encypherment.
The message is message.json file with "cyphertext", "sender", "hash" and "reference" fields.
These are 2 different values.
First I talked about the documentHash in fact, not about messageHash.

**Comment by onthebreeze** [comment]
The "hash" property of the TAP message header IS supposed to he the hash of the signed document before encryption.  So we are talking about the same thing.

**Comment by monkeypants** [comment]
Note: #22 adds message lifecycle stuff from this ticket

**Comment by monkeypants** [comment]
Given all the OT suggestions are now in their own tickets, and 5482d24 is merged, I think this ticket is done
