### ISSUE TITLE
update spec: add recipientParticiparntIdentifier as a header parameter

### ISSUE THREAD

**Issue by kshychko** [ausdigital/ausdigital-tap#24]
A recipient Participant Identifier should be passed to TAP within a POST message request,
Reasons for that:

1. add an opportunity for TAP endpoint to "validate itself" - check if it is a correct receiver according to DCL/DCP. In this case the receiver will be able to respond properly - provide the correct endpoint according to DCL/DCP or suggest try again later if endpoint's records are not up to date .
2. specify a receiver identifier which will be used as a responded identifier in case if the same TAP endpoint serves for different type of identifier for the same participant.

Proposal:
add a request parameter "recipientParticipantIdentifier", type - string, location - header.

Question:
should we make this parameter optional?

**Comment by monkeypants** [comment]
Is it a good thing that the TAP knows who/what it is handling? Maybe it's a good thing if we keep them ignorant...

**Comment by monkeypants** [comment]
per 18#issuecomment-305977776, I'd like to propose an alternative:

 * we don't include recipientParticipantID in messages.
 * the first message in a conversation has senderParticipantID + initiatorReference (which must be unique for the sender)
 * for all messages in the conversation, initiatorParticipantID == the initial message senderParticipantID
 * when the first message is successfully delivered (callback message "delivered" per #22/#28, after signatures checked etc), then our callback message and all subsequent messages in the conversation all include the tripple (InitiatorParticipantID, initiatorReference, responderParticipantID).
 * all messages always contain senderParticipantID.

**Comment by kshychko** [comment]
closing the issue as an alternative approach is chosen - #34
