### ISSUE TITLE
question: should LAPGW verify signatures?

### ISSUE THREAD

**Issue by monkeypants** [ausdigital/ausdigital-tap#7]
This page http://access-point.readthedocs.io/en/latest/introduction/ used to say

```
TODO: is a LAPGW is responsible for signature validation? I think it's just a
curtesy, if you want to be sure check it yourself.
```

I took out that comment and made this ticket for discussion.

**Comment by monkeypants** [comment]
I think that the TAP:
 * MAY reject messages with an invalid signature (giving the invalid signature error message)
 * If error callback provided with submission, and signature does not pass validation, then the TAP MUST make error callback with submission ID and invalid signature error message. 

and the TAP-GW:
 * MAY refuse to send messages with an invalid signature (giving the invalid signature error message)

**Comment by koriaf** [comment]
Verification of signature is an important step, because without it you can't rely on message content - anyone can claim sender field value, but only real sender may provider valid signature.
and in case of tap and tap-gw I think it's okay to verify signature on first trusted endpoint (client uses tap-gw, tap-gw verifies incoming signatures, and client trusts tap-gw to verify it).

**Comment by monkeypants** [comment]
Yes, but of course the ledger doesn't have to trust the TAP-GW, and can re-verify for themselves if they wish.

**Comment by koriaf** [comment]
in this case we need to add /signature/ endpoint which return signature content, because now we return only message metadata and body :-)

**Comment by monkeypants** [comment]
do you think we should do that?

**Comment by koriaf** [comment]
no, while our cyphertext contains already signed document (signed with the same keys as the message).

**Comment by monkeypants** [comment]
So ledger has signed cyphertext, and they can check Sig after they decrypt. They are not forced to trust the gateway. Ok.

What's left to do here? Update TAP spec ? TAP-GW? Enumerate sigcheck-fail error message, callback and status? What else?
