### ISSUE TITLE
Comments on the TAP Spec

### ISSUE THREAD

**Issue by onthebreeze** [ausdigital/ausdigital-tap#8]
In http://access-point.readthedocs.io/en/latest/introduction/
- Should IDP be a spec on which the TAP depends?
- NRY should be an optional dependency

Similarly in http://access-point.readthedocs.io/en/latest/tap_details/ the TAP "optionally" notarises...

Update http://access-point.readthedocs.io/en/latest/transactions/ to reflect the generic DCL lookup / SMP lookup / create secure envelepe / POST message / GET status...  Ie remove all invoice specific semantics.

**Comment by monkeypants** [comment]
I agree the TAP depends on IDP (and optionally on NRY). We should call that out in the front matter and reiterate in details.

The transactions page is obsolete, but that's a separate issue (new ticket needed)

**Comment by koriaf** [comment]
I think the whole task is obsolette and may be closed.

**Comment by monkeypants** [comment]
Agreed
